#
# Properties for local development only
#

# Configure embedded app server
server:
  port: 7778

# Netflix Eureka Client configuration
eureka:
  instance:
    nonSecurePort: ${server.port}
    #    ipAddress: <my network IP address>
    leaseRenewalIntervalInSeconds: 10 # For development only
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

spring:
  #  activemq:
  #    broker-url: tcp://localhost:61616
  # Disable Spring JMS
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
  # ldap server configuration
  ldap:
    embedded:
      ldif: classpath:users.ldif
      base-dn: dc=backbase,dc=com
      port: 8389
#
# Enable debug logging level configuration
#
logging:
  level:
    root: INFO
    com.backbase.service.auth: INFO

#
# External JWT lifetime configuration
#
sso:
  jwt:
    external:
      type: signedEncrypted
      expiration: 3000
      renew: 1000
      not_valid_after: 5000

# ldap spring config
ldap:
  server:
    config:
      userDnPatter: uid={0},ou=users
      searchBase: ou=groups
      url: ldap://localhost:8389/dc=backbase,dc=com
      passwordAttribute: userPassword