server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    appname: ${spring.application.name}
    healthCheckUrlPath: /production-support/health
    statusPageUrlPath: /production-support/info
    nonSecurePort: ${server.port}
    metadata-map:
      # TODO 9: Make this service public available to the Edge Service
      role: live
  client:
    serviceUrl:
      # TODO 10: Use the correct port for your Registry
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8761}/registry/eureka/

# Logging
logging:
  level:
    root: INFO
    com.backbase: INFO
    org.springframework: INFO

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      type: signed
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Define app defaults
spring:
  jmx:
    enabled: false

# Spring health monitoring
management:
  health:
    jms:
      enabled: false