/*
 * clients
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Address Data Transfer Object
 */
@ApiModel(description = "Address Data Transfer Object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-17T14:40:27.775Z")
public class Address {
    @SerializedName("encodedKey")
    private String encodedKey = null;

    @SerializedName("parentKey")
    private String parentKey = null;

    @SerializedName("line1")
    private String line1 = null;

    @SerializedName("line2")
    private String line2 = null;

    @SerializedName("city")
    private String city = null;

    @SerializedName("region")
    private String region = null;

    @SerializedName("postcode")
    private String postcode = null;

    @SerializedName("country")
    private String country = null;

    @SerializedName("indexInList")
    private Integer indexInList = null;

    @SerializedName("latitude")
    private BigDecimal latitude = null;

    @SerializedName("longitude")
    private BigDecimal longitude = null;

    /**
     * Address encoded key, unique, generated
     *
     * @return encodedKey
     **/
    @ApiModelProperty(value = "Address encoded key, unique, generated")
    public String getEncodedKey() {
        return encodedKey;
    }

    /**
     * Address parent key, the object owning this address, client, centre, branch
     *
     * @return parentKey
     **/
    @ApiModelProperty(value = "Address parent key, the object owning this address, client, centre, branch")
    public String getParentKey() {
        return parentKey;
    }

    public Address line1(String line1) {
        this.line1 = line1;
        return this;
    }

    /**
     * The first line of the address
     *
     * @return line1
     **/
    @ApiModelProperty(value = "The first line of the address")
    public String getLine1() {
        return line1;
    }

    public void setLine1(String line1) {
        this.line1 = line1;
    }

    public Address line2(String line2) {
        this.line2 = line2;
        return this;
    }

    /**
     * The second line for the address, in case the first one doesn&#39;t fit the information, this is completely optional
     *
     * @return line2
     **/
    @ApiModelProperty(value = "The second line for the address, in case the first one doesn't fit the information, this is completely optional")
    public String getLine2() {
        return line2;
    }

    public void setLine2(String line2) {
        this.line2 = line2;
    }

    public Address city(String city) {
        this.city = city;
        return this;
    }

    /**
     * The city for this address
     *
     * @return city
     **/
    @ApiModelProperty(value = "The city for this address")
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Address region(String region) {
        this.region = region;
        return this;
    }

    /**
     * The region that is part of the address
     *
     * @return region
     **/
    @ApiModelProperty(value = "The region that is part of the address")
    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Address postcode(String postcode) {
        this.postcode = postcode;
        return this;
    }

    /**
     * The post code
     *
     * @return postcode
     **/
    @ApiModelProperty(value = "The post code")
    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public Address country(String country) {
        this.country = country;
        return this;
    }

    /**
     * The country
     *
     * @return country
     **/
    @ApiModelProperty(value = "The country")
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Address indexInList(Integer indexInList) {
        this.indexInList = indexInList;
        return this;
    }

    /**
     * Index of this address in the list of addresses
     *
     * @return indexInList
     **/
    @ApiModelProperty(value = "Index of this address in the list of addresses")
    public Integer getIndexInList() {
        return indexInList;
    }

    public void setIndexInList(Integer indexInList) {
        this.indexInList = indexInList;
    }

    public Address latitude(BigDecimal latitude) {
        this.latitude = latitude;
        return this;
    }

    /**
     * The GPS latitude of this address in signed degrees format (DDD.dddd) with 6 decimal positions, ranging from -90 to +90
     *
     * @return latitude
     **/
    @ApiModelProperty(value = "The GPS latitude of this address in signed degrees format (DDD.dddd) with 6 decimal positions, ranging from -90 to +90")
    public BigDecimal getLatitude() {
        return latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public Address longitude(BigDecimal longitude) {
        this.longitude = longitude;
        return this;
    }

    /**
     * The GPS longitude of this address in signed degrees format (DDD.dddd) with 6 decimal positions, ranging from -180 to +180
     *
     * @return longitude
     **/
    @ApiModelProperty(value = "The GPS longitude of this address in signed degrees format (DDD.dddd) with 6 decimal positions, ranging from -180 to +180")
    public BigDecimal getLongitude() {
        return longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Address address = (Address) o;
        return Objects.equals(this.encodedKey, address.encodedKey) &&
                Objects.equals(this.parentKey, address.parentKey) &&
                Objects.equals(this.line1, address.line1) &&
                Objects.equals(this.line2, address.line2) &&
                Objects.equals(this.city, address.city) &&
                Objects.equals(this.region, address.region) &&
                Objects.equals(this.postcode, address.postcode) &&
                Objects.equals(this.country, address.country) &&
                Objects.equals(this.indexInList, address.indexInList) &&
                Objects.equals(this.latitude, address.latitude) &&
                Objects.equals(this.longitude, address.longitude);
    }

    @Override
    public int hashCode() {
        return Objects.hash(encodedKey, parentKey, line1, line2, city, region, postcode, country, indexInList, latitude, longitude);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Address {\n");

        sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
        sb.append("    parentKey: ").append(toIndentedString(parentKey)).append("\n");
        sb.append("    line1: ").append(toIndentedString(line1)).append("\n");
        sb.append("    line2: ").append(toIndentedString(line2)).append("\n");
        sb.append("    city: ").append(toIndentedString(city)).append("\n");
        sb.append("    region: ").append(toIndentedString(region)).append("\n");
        sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
        sb.append("    country: ").append(toIndentedString(country)).append("\n");
        sb.append("    indexInList: ").append(toIndentedString(indexInList)).append("\n");
        sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
        sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

