/*
 * clients
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.io.IOException;
import java.util.Objects;

/**
 * Portal settings for an individual client
 */
@ApiModel(description = "Portal settings for an individual client")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-17T14:40:27.775Z")
public class PortalSettings {
    @SerializedName("encodedKey")
    private String encodedKey = null;
    @SerializedName("portalState")
    private PortalStateEnum portalState = null;
    @SerializedName("lastLoggedInDate")
    private OffsetDateTime lastLoggedInDate = null;

    /**
     * The encoded key of the entity, generated, globally unique
     *
     * @return encodedKey
     **/
    @ApiModelProperty(value = "The encoded key of the entity, generated, globally unique")
    public String getEncodedKey() {
        return encodedKey;
    }

    public PortalSettings portalState(PortalStateEnum portalState) {
        this.portalState = portalState;
        return this;
    }

    /**
     * State of the client&#39;s portal preferences
     *
     * @return portalState
     **/
    @ApiModelProperty(value = "State of the client's portal preferences")
    public PortalStateEnum getPortalState() {
        return portalState;
    }

    public void setPortalState(PortalStateEnum portalState) {
        this.portalState = portalState;
    }

    public PortalSettings lastLoggedInDate(OffsetDateTime lastLoggedInDate) {
        this.lastLoggedInDate = lastLoggedInDate;
        return this;
    }

    /**
     * The last date the client logged in to the portal
     *
     * @return lastLoggedInDate
     **/
    @ApiModelProperty(example = "2016-09-06T13:37:50+03:00", value = "The last date the client logged in to the portal")
    public OffsetDateTime getLastLoggedInDate() {
        return lastLoggedInDate;
    }

    public void setLastLoggedInDate(OffsetDateTime lastLoggedInDate) {
        this.lastLoggedInDate = lastLoggedInDate;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PortalSettings portalSettings = (PortalSettings) o;
        return Objects.equals(this.encodedKey, portalSettings.encodedKey) &&
                Objects.equals(this.portalState, portalSettings.portalState) &&
                Objects.equals(this.lastLoggedInDate, portalSettings.lastLoggedInDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(encodedKey, portalState, lastLoggedInDate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PortalSettings {\n");

        sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
        sb.append("    portalState: ").append(toIndentedString(portalState)).append("\n");
        sb.append("    lastLoggedInDate: ").append(toIndentedString(lastLoggedInDate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * State of the client&#39;s portal preferences
     */
    @JsonAdapter(PortalStateEnum.Adapter.class)
    public enum PortalStateEnum {
        ENABLED("ENABLED"),

        DISABLED("DISABLED");

        private String value;

        PortalStateEnum(String value) {
            this.value = value;
        }

        public static PortalStateEnum fromValue(String text) {
            for (PortalStateEnum b : PortalStateEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<PortalStateEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final PortalStateEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public PortalStateEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return PortalStateEnum.fromValue(String.valueOf(value));
            }
        }
    }

}

