/*
 * deposits
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Groups all fields related to a deposit account&#39;s accrued amounts
 */
@ApiModel(description = "Groups all fields related to a deposit account's accrued amounts")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-17T14:24:31.447Z")
public class DepositAccountAccruedAmounts {

    @SerializedName("interestAccrued")
    private BigDecimal interestAccrued = null;

    @SerializedName("overdraftInterestAccrued")
    private BigDecimal overdraftInterestAccrued = null;

    @SerializedName("technicalOverdraftInterestAccrued")
    private BigDecimal technicalOverdraftInterestAccrued = null;

    /**
     * The amount of interest that has been accrued in the account
     *
     * @return interestAccrued
     **/
    @ApiModelProperty(value = "The amount of interest that has been accrued in the account")
    public BigDecimal getInterestAccrued() {
        return interestAccrued;
    }

    public void setInterestAccrued(BigDecimal interestAccrued) {
        this.interestAccrued = interestAccrued;
    }

    /**
     * The amount of overdraft interest that has been accrued in the account
     *
     * @return overdraftInterestAccrued
     **/
    @ApiModelProperty(value = "The amount of overdraft interest that has been accrued in the account")
    public BigDecimal getOverdraftInterestAccrued() {
        return overdraftInterestAccrued;
    }

    /**
     * The amount of technical overdraft interest that has been accrued in the account
     *
     * @return technicalOverdraftInterestAccrued
     **/
    @ApiModelProperty(value = "The amount of technical overdraft interest that has been accrued in the account")
    public BigDecimal getTechnicalOverdraftInterestAccrued() {
        return technicalOverdraftInterestAccrued;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DepositAccountAccruedAmounts depositAccountAccruedAmounts = (DepositAccountAccruedAmounts) o;
        return Objects.equals(this.interestAccrued, depositAccountAccruedAmounts.interestAccrued) &&
                Objects.equals(this.overdraftInterestAccrued, depositAccountAccruedAmounts.overdraftInterestAccrued) &&
                Objects.equals(this.technicalOverdraftInterestAccrued, depositAccountAccruedAmounts.technicalOverdraftInterestAccrued);
    }

    @Override
    public int hashCode() {
        return Objects.hash(interestAccrued, overdraftInterestAccrued, technicalOverdraftInterestAccrued);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DepositAccountAccruedAmounts {\n");

        sb.append("    interestAccrued: ").append(toIndentedString(interestAccrued)).append("\n");
        sb.append("    overdraftInterestAccrued: ").append(toIndentedString(overdraftInterestAccrued)).append("\n");
        sb.append("    technicalOverdraftInterestAccrued: ").append(toIndentedString(technicalOverdraftInterestAccrued)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

