/*
 * deposits
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Overdraft interest rate settings for deposit accounts
 */
@ApiModel(description = "Overdraft interest rate settings for deposit accounts")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-17T14:24:31.447Z")
public class DepositAccountOverdraftInterestRateSettings {
    @SerializedName("encodedKey")
    private String encodedKey = null;

    @SerializedName("interestRate")
    private BigDecimal interestRate = null;
    @SerializedName("interestChargeFrequency")
    private InterestChargeFrequencyEnum interestChargeFrequency = null;
    @SerializedName("interestChargeFrequencyCount")
    private Integer interestChargeFrequencyCount = null;
    @SerializedName("interestRateTiers")
    private List<DepositAccountInterestRateTier> interestRateTiers = null;
    @SerializedName("interestRateTerms")
    private InterestRateTermsEnum interestRateTerms = null;
    @SerializedName("interestSpread")
    private BigDecimal interestSpread = null;
    @SerializedName("interestRateReviewCount")
    private Integer interestRateReviewCount = null;
    @SerializedName("interestRateSource")
    private InterestRateSourceEnum interestRateSource = null;
    @SerializedName("interestRateReviewUnit")
    private InterestRateReviewUnitEnum interestRateReviewUnit = null;

    /**
     * The encoded for this set of interest settings, auto generated, unique
     *
     * @return encodedKey
     **/
    @ApiModelProperty(value = "The encoded for this set of interest settings, auto generated, unique")
    public String getEncodedKey() {
        return encodedKey;
    }

    public DepositAccountOverdraftInterestRateSettings interestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
        return this;
    }

    /**
     * The interest rate for the deposit account
     *
     * @return interestRate
     **/
    @ApiModelProperty(value = "The interest rate for the deposit account")
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    public DepositAccountOverdraftInterestRateSettings interestChargeFrequency(InterestChargeFrequencyEnum interestChargeFrequency) {
        this.interestChargeFrequency = interestChargeFrequency;
        return this;
    }

    /**
     * The interest change frequency. Holds the possible values for how often is interest charged on loan or deposit accounts
     *
     * @return interestChargeFrequency
     **/
    @ApiModelProperty(value = "The interest change frequency. Holds the possible values for how often is interest charged on loan or deposit accounts")
    public InterestChargeFrequencyEnum getInterestChargeFrequency() {
        return interestChargeFrequency;
    }

    public void setInterestChargeFrequency(InterestChargeFrequencyEnum interestChargeFrequency) {
        this.interestChargeFrequency = interestChargeFrequency;
    }

    public DepositAccountOverdraftInterestRateSettings interestChargeFrequencyCount(Integer interestChargeFrequencyCount) {
        this.interestChargeFrequencyCount = interestChargeFrequencyCount;
        return this;
    }

    /**
     * The count of units to apply over the interval (e.g. [x] weeks)
     *
     * @return interestChargeFrequencyCount
     **/
    @ApiModelProperty(value = "The count of units to apply over the interval (e.g. [x] weeks)")
    public Integer getInterestChargeFrequencyCount() {
        return interestChargeFrequencyCount;
    }

    public void setInterestChargeFrequencyCount(Integer interestChargeFrequencyCount) {
        this.interestChargeFrequencyCount = interestChargeFrequencyCount;
    }

    public DepositAccountOverdraftInterestRateSettings interestRateTiers(List<DepositAccountInterestRateTier> interestRateTiers) {
        this.interestRateTiers = interestRateTiers;
        return this;
    }

    public DepositAccountOverdraftInterestRateSettings addInterestRateTiersItem(DepositAccountInterestRateTier interestRateTiersItem) {
        if (this.interestRateTiers == null) {
            this.interestRateTiers = new ArrayList<DepositAccountInterestRateTier>();
        }
        this.interestRateTiers.add(interestRateTiersItem);
        return this;
    }

    /**
     * The list of interest rate tiers. An interest rate tier holds the values to define how the interest is computed
     *
     * @return interestRateTiers
     **/
    @ApiModelProperty(value = "The list of interest rate tiers. An interest rate tier holds the values to define how the interest is computed")
    public List<DepositAccountInterestRateTier> getInterestRateTiers() {
        return interestRateTiers;
    }

    public void setInterestRateTiers(List<DepositAccountInterestRateTier> interestRateTiers) {
        this.interestRateTiers = interestRateTiers;
    }

    public DepositAccountOverdraftInterestRateSettings interestRateTerms(InterestRateTermsEnum interestRateTerms) {
        this.interestRateTerms = interestRateTerms;
        return this;
    }

    /**
     * How is the interest rate determined when being accrued for an account
     *
     * @return interestRateTerms
     **/
    @ApiModelProperty(value = "How is the interest rate determined when being accrued for an account")
    public InterestRateTermsEnum getInterestRateTerms() {
        return interestRateTerms;
    }

    public void setInterestRateTerms(InterestRateTermsEnum interestRateTerms) {
        this.interestRateTerms = interestRateTerms;
    }

    public DepositAccountOverdraftInterestRateSettings interestSpread(BigDecimal interestSpread) {
        this.interestSpread = interestSpread;
        return this;
    }

    /**
     * The rate based on which the interest is accrued and applied for accounts with InterestRateSource#INDEX_INTEREST_RATE
     *
     * @return interestSpread
     **/
    @ApiModelProperty(value = "The rate based on which the interest is accrued and applied for accounts with InterestRateSource#INDEX_INTEREST_RATE")
    public BigDecimal getInterestSpread() {
        return interestSpread;
    }

    public void setInterestSpread(BigDecimal interestSpread) {
        this.interestSpread = interestSpread;
    }

    public DepositAccountOverdraftInterestRateSettings interestRateReviewCount(Integer interestRateReviewCount) {
        this.interestRateReviewCount = interestRateReviewCount;
        return this;
    }

    /**
     * The interest rate review frequency unit count
     *
     * @return interestRateReviewCount
     **/
    @ApiModelProperty(value = "The interest rate review frequency unit count")
    public Integer getInterestRateReviewCount() {
        return interestRateReviewCount;
    }

    public void setInterestRateReviewCount(Integer interestRateReviewCount) {
        this.interestRateReviewCount = interestRateReviewCount;
    }

    /**
     * The interest rate source. Represents the interest calculation method
     *
     * @return interestRateSource
     **/
    @ApiModelProperty(value = "The interest rate source. Represents the interest calculation method")
    public InterestRateSourceEnum getInterestRateSource() {
        return interestRateSource;
    }

    public DepositAccountOverdraftInterestRateSettings interestRateReviewUnit(InterestRateReviewUnitEnum interestRateReviewUnit) {
        this.interestRateReviewUnit = interestRateReviewUnit;
        return this;
    }

    /**
     * The interest rate review frequency measurement unit
     *
     * @return interestRateReviewUnit
     **/
    @ApiModelProperty(value = "The interest rate review frequency measurement unit")
    public InterestRateReviewUnitEnum getInterestRateReviewUnit() {
        return interestRateReviewUnit;
    }

    public void setInterestRateReviewUnit(InterestRateReviewUnitEnum interestRateReviewUnit) {
        this.interestRateReviewUnit = interestRateReviewUnit;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DepositAccountOverdraftInterestRateSettings depositAccountOverdraftInterestRateSettings = (DepositAccountOverdraftInterestRateSettings) o;
        return Objects.equals(this.encodedKey, depositAccountOverdraftInterestRateSettings.encodedKey) &&
                Objects.equals(this.interestRate, depositAccountOverdraftInterestRateSettings.interestRate) &&
                Objects.equals(this.interestChargeFrequency, depositAccountOverdraftInterestRateSettings.interestChargeFrequency) &&
                Objects.equals(this.interestChargeFrequencyCount, depositAccountOverdraftInterestRateSettings.interestChargeFrequencyCount) &&
                Objects.equals(this.interestRateTiers, depositAccountOverdraftInterestRateSettings.interestRateTiers) &&
                Objects.equals(this.interestRateTerms, depositAccountOverdraftInterestRateSettings.interestRateTerms) &&
                Objects.equals(this.interestSpread, depositAccountOverdraftInterestRateSettings.interestSpread) &&
                Objects.equals(this.interestRateReviewCount, depositAccountOverdraftInterestRateSettings.interestRateReviewCount) &&
                Objects.equals(this.interestRateSource, depositAccountOverdraftInterestRateSettings.interestRateSource) &&
                Objects.equals(this.interestRateReviewUnit, depositAccountOverdraftInterestRateSettings.interestRateReviewUnit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(encodedKey, interestRate, interestChargeFrequency, interestChargeFrequencyCount, interestRateTiers, interestRateTerms, interestSpread, interestRateReviewCount, interestRateSource, interestRateReviewUnit);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DepositAccountOverdraftInterestRateSettings {\n");

        sb.append("    encodedKey: ").append(toIndentedString(encodedKey)).append("\n");
        sb.append("    interestRate: ").append(toIndentedString(interestRate)).append("\n");
        sb.append("    interestChargeFrequency: ").append(toIndentedString(interestChargeFrequency)).append("\n");
        sb.append("    interestChargeFrequencyCount: ").append(toIndentedString(interestChargeFrequencyCount)).append("\n");
        sb.append("    interestRateTiers: ").append(toIndentedString(interestRateTiers)).append("\n");
        sb.append("    interestRateTerms: ").append(toIndentedString(interestRateTerms)).append("\n");
        sb.append("    interestSpread: ").append(toIndentedString(interestSpread)).append("\n");
        sb.append("    interestRateReviewCount: ").append(toIndentedString(interestRateReviewCount)).append("\n");
        sb.append("    interestRateSource: ").append(toIndentedString(interestRateSource)).append("\n");
        sb.append("    interestRateReviewUnit: ").append(toIndentedString(interestRateReviewUnit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    /**
     * The interest change frequency. Holds the possible values for how often is interest charged on loan or deposit accounts
     */
    @JsonAdapter(InterestChargeFrequencyEnum.Adapter.class)
    public enum InterestChargeFrequencyEnum {
        ANNUALIZED("ANNUALIZED"),

        EVERY_MONTH("EVERY_MONTH"),

        EVERY_FOUR_WEEKS("EVERY_FOUR_WEEKS"),

        EVERY_WEEK("EVERY_WEEK"),

        EVERY_DAY("EVERY_DAY"),

        EVERY_X_DAYS("EVERY_X_DAYS");

        private String value;

        InterestChargeFrequencyEnum(String value) {
            this.value = value;
        }

        public static InterestChargeFrequencyEnum fromValue(String text) {
            for (InterestChargeFrequencyEnum b : InterestChargeFrequencyEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<InterestChargeFrequencyEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final InterestChargeFrequencyEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public InterestChargeFrequencyEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return InterestChargeFrequencyEnum.fromValue(String.valueOf(value));
            }
        }
    }

    /**
     * How is the interest rate determined when being accrued for an account
     */
    @JsonAdapter(InterestRateTermsEnum.Adapter.class)
    public enum InterestRateTermsEnum {
        FIXED("FIXED"),

        TIERED("TIERED"),

        TIERED_PERIOD("TIERED_PERIOD");

        private String value;

        InterestRateTermsEnum(String value) {
            this.value = value;
        }

        public static InterestRateTermsEnum fromValue(String text) {
            for (InterestRateTermsEnum b : InterestRateTermsEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<InterestRateTermsEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final InterestRateTermsEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public InterestRateTermsEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return InterestRateTermsEnum.fromValue(String.valueOf(value));
            }
        }
    }


    /**
     * The interest rate source. Represents the interest calculation method
     */
    @JsonAdapter(InterestRateSourceEnum.Adapter.class)
    public enum InterestRateSourceEnum {
        FIXED_INTEREST_RATE("FIXED_INTEREST_RATE"),

        INDEX_INTEREST_RATE("INDEX_INTEREST_RATE");

        private String value;

        InterestRateSourceEnum(String value) {
            this.value = value;
        }

        public static InterestRateSourceEnum fromValue(String text) {
            for (InterestRateSourceEnum b : InterestRateSourceEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<InterestRateSourceEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final InterestRateSourceEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public InterestRateSourceEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return InterestRateSourceEnum.fromValue(String.valueOf(value));
            }
        }
    }

    /**
     * The interest rate review frequency measurement unit
     */
    @JsonAdapter(InterestRateReviewUnitEnum.Adapter.class)
    public enum InterestRateReviewUnitEnum {
        DAYS("DAYS"),

        WEEKS("WEEKS"),

        MONTHS("MONTHS");

        private String value;

        InterestRateReviewUnitEnum(String value) {
            this.value = value;
        }

        public static InterestRateReviewUnitEnum fromValue(String text) {
            for (InterestRateReviewUnitEnum b : InterestRateReviewUnitEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static class Adapter extends TypeAdapter<InterestRateReviewUnitEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final InterestRateReviewUnitEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public InterestRateReviewUnitEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return InterestRateReviewUnitEnum.fromValue(String.valueOf(value));
            }
        }
    }

}

