/*
 * deposits
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Groups all fields related to a deposit account&#39;s overdraft interest settings
 */
@ApiModel(description = "Groups all fields related to a deposit account's overdraft interest settings")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-17T14:24:31.447Z")
public class DepositAccountOverdraftInterestSettings {
    @SerializedName("interestRateSettings")
    private DepositAccountOverdraftInterestRateSettings interestRateSettings = null;

    public DepositAccountOverdraftInterestSettings interestRateSettings(DepositAccountOverdraftInterestRateSettings interestRateSettings) {
        this.interestRateSettings = interestRateSettings;
        return this;
    }

    /**
     * Overdraft interest rate settings for deposit accounts
     *
     * @return interestRateSettings
     **/
    @ApiModelProperty(value = "Overdraft interest rate settings for deposit accounts")
    public DepositAccountOverdraftInterestRateSettings getInterestRateSettings() {
        return interestRateSettings;
    }

    public void setInterestRateSettings(DepositAccountOverdraftInterestRateSettings interestRateSettings) {
        this.interestRateSettings = interestRateSettings;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DepositAccountOverdraftInterestSettings depositAccountOverdraftInterestSettings = (DepositAccountOverdraftInterestSettings) o;
        return Objects.equals(this.interestRateSettings, depositAccountOverdraftInterestSettings.interestRateSettings);
    }

    @Override
    public int hashCode() {
        return Objects.hash(interestRateSettings);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DepositAccountOverdraftInterestSettings {\n");

        sb.append("    interestRateSettings: ").append(toIndentedString(interestRateSettings)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

