/*
 * deposits
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.mambu.sdk.model.v2;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Wrapper for month and day for instances where the year isn&#39;t needed
 */
@ApiModel(description = "Wrapper for month and day for instances where the year isn't needed")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-17T14:24:31.447Z")
public class MonthAndDay {
    @SerializedName("month")
    private Integer month = null;

    @SerializedName("day")
    private Integer day = null;

    public MonthAndDay month(Integer month) {
        this.month = month;
        return this;
    }

    /**
     * The month of the year
     *
     * @return month
     **/
    @ApiModelProperty(value = "The month of the year")
    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public MonthAndDay day(Integer day) {
        this.day = day;
        return this;
    }

    /**
     * The day in the month
     *
     * @return day
     **/
    @ApiModelProperty(value = "The day in the month")
    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MonthAndDay monthAndDay = (MonthAndDay) o;
        return Objects.equals(this.month, monthAndDay.month) &&
                Objects.equals(this.day, monthAndDay.day);
    }

    @Override
    public int hashCode() {
        return Objects.hash(month, day);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MonthAndDay {\n");

        sb.append("    month: ").append(toIndentedString(month)).append("\n");
        sb.append("    day: ").append(toIndentedString(day)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

