package com.backbase;

import com.openbankproject.api.spec.ATMApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 *
 *  Configuration using ATMApi generated by the swagger codegen plugin from the swagger spec
 */

@Configuration
public class OpenBankConfiguration {

    @Bean
    public ATMApi getATMApi() {
        return new ATMApi();
    }

}
