server:
  port: 9921
spring:
  activemq:
    broker-url: ${activemq.url:tcp://localhost:61616}
  jmx:
    default-domain: ${spring.application.name}
  jta:
    logDir: target/${spring.application.name}-logs

backbase:
  web:
    security:
      enabled: true

sso:
  jwt:
    internal:
      type: signed
      signature:
        algorithm: HS256
        key:
          type: ENV
          value: SIG_SECRET_KEY
eureka:
  instance:
    metadata-map:
      public: false
      role: live
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST:localhost}:${REGISTRY_PORT:8080}/registry/eureka/

openbankproject:
  transactions:
    url: https://apisandbox.openbankproject.com/obp/v1.2.1/banks/rbs/accounts/savings-kids-john/public/transactions